// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PruvodceProject.Data;

#nullable disable

namespace PruvodceProject.Migrations
{
    [DbContext(typeof(PruvodceData))]
    [Migration("20231008154912_model_a_vazba_budova_foto")]
    partial class model_a_vazba_budova_foto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PruvodceProject.Models.AutomatyModel", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("bagety")
                        .HasColumnType("bit");

                    b.Property<string>("budova")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("patro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("typ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Automaty");
                });

            modelBuilder.Entity("PruvodceProject.Models.BudovyModel", b =>
                {
                    b.Property<Guid>("IdBudovy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kodoveOznaceni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdBudovy");

                    b.ToTable("Budovy");
                });

            modelBuilder.Entity("PruvodceProject.Models.PhotoModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BudovyIdBudovy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("DataPhoto")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid>("IdBudovy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pripona")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BudovyIdBudovy");

                    b.ToTable("Photo");
                });

            modelBuilder.Entity("PruvodceProject.Models.StravovaciZarizeniModel", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nazev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("odkazNaMenu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("popis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("StravovaciZarizeni");
                });

            modelBuilder.Entity("PruvodceProject.Models.Ucebna", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("druh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("patro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ucebna");
                });

            modelBuilder.Entity("PruvodceProject.Models.UserModel", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("heslo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("PrihlasovaciUdaje");
                });

            modelBuilder.Entity("PruvodceProject.Models.UserVerify", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("expirace")
                        .HasColumnType("datetime2");

                    b.Property<string>("heslo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("kod")
                        .HasColumnType("int");

                    b.Property<string>("mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("OverovaciUdaje");
                });

            modelBuilder.Entity("PruvodceProject.Models.PhotoModel", b =>
                {
                    b.HasOne("PruvodceProject.Models.BudovyModel", "Budovy")
                        .WithMany("fotky")
                        .HasForeignKey("BudovyIdBudovy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Budovy");
                });

            modelBuilder.Entity("PruvodceProject.Models.BudovyModel", b =>
                {
                    b.Navigation("fotky");
                });
#pragma warning restore 612, 618
        }
    }
}
